package accounts

import (
	"context"
	"time"
)

// AuthDriver is the provider-neutral contract every credential flow
// implements. The interface is provider-neutral and intentionally excludes
// browser-flow wiring, which belongs to the admin HTTP package.
//
// All methods take a context and a single input struct. The struct
// fields are explicit rather than positional to keep call sites
// readable. Drivers MUST NOT log raw credentials; they return tokens
// wrapped in *Secret so the contract makes accidental logging hard.
type AuthDriver interface {
	// Kind reports the credential kind this driver handles.
	Kind() CredentialKind

	// Start kicks off either an authorization-code or device-code
	// flow, depending on input.Flow. The result includes either a
	// user-facing URL (browser) or a user code + verification URL
	// (device). For PKCE flows the driver fills CodeChallenge.
	Start(ctx context.Context, input OAuthStartInput) (*OAuthStartResult, error)

	// Poll advances a device-code flow. Returns the current status
	// and, when completed, the resulting token set.
	Poll(ctx context.Context, state string) (*OAuthPollResult, error)

	// Exchange completes an authorization-code flow by redeeming the
	// returned code for a token set.
	Exchange(ctx context.Context, input OAuthExchangeInput) (*TokenSet, error)

	// Refresh mints a new access token using the supplied refresh
	// token. Implementations MUST classify the failure into one of
	// ErrKindReauthentication, ErrKindRefreshTransient, or
	// ErrKindRefreshFatal so callers can pick the right policy.
	Refresh(ctx context.Context, input RefreshTokenInput) (*TokenSet, error)

	// Revoke invalidates the supplied token at the provider. Best
	// effort: a not-supported error is acceptable.
	Revoke(ctx context.Context, input RevokeTokenInput) error
}

// Capabilities declares the flow operations a driver implements. The values
// are provider-neutral and are safe to expose in the admin catalog.
type Capabilities struct {
	Browser    bool
	Device     bool
	Poll       bool
	Exchange   bool
	Refresh    bool
	Revoke     bool
	AccessOnly bool
}

// DriverInfo is an optional additive identity contract. Keeping it separate
// preserves source compatibility for existing AuthDriver test doubles.
type DriverInfo interface {
	ID() string
	Capabilities() Capabilities
}

// OAuthStartInput is the input to AuthDriver.Start.
type OAuthStartInput struct {
	// ProviderID identifies the upstream.
	ProviderID string
	// RedirectURI is required for browser flows, ignored for device.
	RedirectURI string
	// Scopes is the requested scope set. Providers may ignore or
	// override.
	Scopes []string
	// State is the caller-supplied CSRF token. Drivers should
	// generate one if empty.
	State string
	// CodeChallenge is the PKCE challenge, when the driver opts
	// into PKCE. The driver returns the matching verifier
	// separately if needed.
	CodeChallenge string
	// CodeChallengeMethod is "S256" or "plain".
	CodeChallengeMethod string
	// Flow selects browser or device. Empty defaults to "browser".
	Flow        OAuthFlowKind
	AWSMode     string
	AWSStartURL string
	AWSRegion   string
}

// OAuthFlowKind selects the entry flow at Start time.
type OAuthFlowKind string

const (
	// FlowBrowser runs the authorization-code redirect flow.
	FlowBrowser OAuthFlowKind = "browser"
	// FlowDevice runs the device-code flow.
	FlowDevice OAuthFlowKind = "device"
)

// OAuthStartResult is the user-facing entry point produced by Start.
type OAuthStartResult struct {
	// AuthorizationURL is the URL the user opens in FlowBrowser.
	AuthorizationURL string
	// State echoes the CSRF token (or the one generated by the
	// driver). Callers MUST verify it on the callback.
	State string
	// ExpiresAt is the wall-clock deadline for the user to
	// complete the flow. Browser flows may have a short window;
	// device flows are usually minutes.
	ExpiresAt time.Time
	// UserCode is the short code the user types at the
	// verification URL in FlowDevice.
	UserCode string
	// VerificationURI is the URL the user visits in FlowDevice.
	VerificationURI string
	// IntervalSeconds is the device-flow poll interval. Callers
	// should wait at least this long between Poll calls.
	IntervalSeconds int
	// CodeVerifier is the PKCE verifier the driver generated.
	// Callers must persist it for the matching callback.
	CodeVerifier string
	// Flow reports which flow was actually started. Useful when
	// the caller asked for "either" and the driver chose one.
	Flow OAuthFlowKind
}

// OAuthPollResult is the device-flow poll result.
type OAuthPollResult struct {
	// Status reports the current state of the flow.
	Status PollStatus
	// IntervalSeconds optionally overrides the next poll delay.
	IntervalSeconds int
	// TokenSet is populated only on StatusCompleted.
	TokenSet *TokenSet
}

// PollStatus enumerates the device-flow outcomes.
type PollStatus string

const (
	// PollPending means the user has not yet completed the flow.
	PollPending PollStatus = "pending"
	// PollCompleted means the flow succeeded and TokenSet is set.
	PollCompleted PollStatus = "completed"
	// PollExpired means the user-code window elapsed.
	PollExpired PollStatus = "expired"
	// PollDenied means the user declined authorization.
	PollDenied PollStatus = "denied"
	// PollError means an upstream failure occurred. The driver
	// may attach error details through the standard error path.
	PollError PollStatus = "error"
)

// OAuthExchangeInput is the input to AuthDriver.Exchange.
type OAuthExchangeInput struct {
	// ProviderID identifies the upstream.
	ProviderID string
	// Code is the authorization code returned to the redirect URI.
	Code string
	// State is the CSRF token from the matching Start call. The
	// driver MUST verify it matches the value it returned.
	State string
	// RedirectURI mirrors the value passed to Start; some
	// providers require an exact match.
	RedirectURI string
	// CodeVerifier is the PKCE verifier, when the Start used PKCE.
	CodeVerifier string
}

// RefreshTokenInput is the input to AuthDriver.Refresh.
type RefreshTokenInput struct {
	// ProviderID identifies the upstream.
	ProviderID string
	// AccountID is the local account the refresh belongs to. May
	// be empty when the driver does not need local context.
	AccountID string
	// RefreshToken is the refresh material. Drivers MUST NOT log
	// it; the Secret wrapper exists to make accidental logging
	// produce a placeholder.
	RefreshToken *Secret
	// Credential is the opaque provider credential bundle
	// (client_id, client_secret, etc.) when the driver needs
	// more than just the refresh token. May be nil.
	Credential *Secret
}

// RevokeTokenInput is the input to AuthDriver.Revoke.
type RevokeTokenInput struct {
	// ProviderID identifies the upstream.
	ProviderID string
	// AccountID is the local account id.
	AccountID string
	// Token is the material to revoke. The driver decides whether
	// to send this as the access token, the refresh token, or
	// both. MUST NOT be logged.
	Token *Secret
}
