-- Adds `telemetry_events.http_status`: the HTTP status the client actually
-- received.
--
-- Why: the `status` enum (`completed`/`failed`/`cancelled`/`truncated`) is the
-- internal terminal state and collapses every failure into one `failed` bucket.
-- The Usage status breakdown needs the real wire code so a 503 admission
-- rejection (`admission_unavailable`, `capacity_exhausted`) is distinguishable
-- from a 500 upstream failure, and so the 499 client-abort bucket is explicit
-- rather than inferred from `status = 'cancelled'`.
--
-- Rows written before this migration carry NULL and are read as "unknown",
-- which is the honest answer for historical data.
--
-- Idempotent: safe to run more than once.
ALTER TABLE telemetry_events ADD COLUMN IF NOT EXISTS http_status integer;
