package adapters

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

const (
	codexClientVersion = "0.144.1"
	codexPiVersion     = "17.1.7"
)

// CodexAdapter is the ChatGPT OAuth Responses adapter. Codex uses the
// Responses wire format, but its backend requires a distinct endpoint,
// identity headers, request metadata, and a stricter request body than the
// public OpenAI API.
type CodexAdapter struct {
	base *OpenAIAdapter
}

// NewCodexAdapter creates the provider-specific Codex Responses adapter.
func NewCodexAdapter(cfg OpenAIAdapterConfig) *CodexAdapter {
	if cfg.ID == "" {
		cfg.ID = "codex"
	}
	if cfg.DisplayName == "" {
		cfg.DisplayName = "Codex ChatGPT"
	}
	if cfg.BaseURL == "" {
		cfg.BaseURL = "https://chatgpt.com/backend-api"
	}
	if len(cfg.Surfaces) == 0 {
		cfg.Surfaces = []Surface{SurfaceOpenAIResponses}
	}
	if cfg.CredentialKind == "" {
		cfg.CredentialKind = CredentialOAuth
	}
	return &CodexAdapter{base: NewOpenAIAdapter(cfg)}
}

func (p *CodexAdapter) Metadata() ProviderMeta       { return p.base.Metadata() }
func (p *CodexAdapter) Capabilities() ProviderCaps   { return p.base.Capabilities() }
func (p *CodexAdapter) Models() ProviderModelCatalog { return p.base.Models() }
func (p *CodexAdapter) ResolveTarget(id string, s Surface) (RouteTarget, error) {
	return p.base.ResolveTarget(id, s)
}

// Endpoint implements the ChatGPT Codex route. The backend base URL is
// https://chatgpt.com/backend-api; the public OpenAI /responses path is not
// valid for this OAuth service.
func (p *CodexAdapter) Endpoint(target RouteTarget) Endpoint {
	return Endpoint{Method: http.MethodPost, Path: "codex/responses"}
}

// AuthMaterial adds the identity headers required by the ChatGPT OAuth
// Responses backend while preserving the bearer credential generated by the
// shared OpenAI adapter.
func (p *CodexAdapter) AuthMaterial(credential string, target RouteTarget) (AuthMaterial, error) {
	auth, err := p.base.AuthMaterial(credential, target)
	if err != nil {
		return AuthMaterial{}, err
	}
	if target.ProviderID != "" && target.ProviderID != "codex" {
		return AuthMaterial{}, &IDMismatchError{AdapterID: "codex", TargetID: target.ProviderID}
	}
	headers := auth.Headers
	headers.Del("x-api-key")
	headers.Set("OpenAI-Beta", "responses=experimental")
	headers.Set("originator", "pi")
	headers.Set("version", codexClientVersion)
	headers.Set("User-Agent", fmt.Sprintf("pi/%s (windows; amd64)", codexPiVersion))
	if accountID := codexAccountID(credential); accountID != "" {
		headers.Set("chatgpt-account-id", accountID)
	}
	return auth, nil
}

// BuildRequest applies Codex's request restrictions and carries stable
// session metadata alongside the prompt cache key. The stable key is reused
// for equivalent instruction/tool prefixes, allowing the upstream prompt
// cache to serve repeated turns without conflating different provider/model
// namespaces.
func (p *CodexAdapter) BuildRequest(envelope RequestEnvelope, credential string) (BuiltRequest, error) {
	built, err := p.base.BuildRequest(envelope, credential)
	if err != nil {
		return BuiltRequest{}, err
	}
	if built.Auth, err = p.AuthMaterial(credential, envelope.Target); err != nil {
		return BuiltRequest{}, err
	}
	var payload map[string]any
	decodeErr := json.Unmarshal(built.Body, &payload)
	if decodeErr != nil || payload == nil {
		err = decodeErr
		if err == nil {
			err = fmt.Errorf("body must be a JSON object")
		}
		return BuiltRequest{}, fmt.Errorf("providers/codex: decode request: %w", err)
	}

	payload["stream"] = true
	for _, field := range []string{
		"max_output_tokens", "max_completion_tokens", "temperature", "top_p", "top_k",
		"min_p", "presence_penalty", "repetition_penalty", "stop",
	} {
		delete(payload, field)
	}

	cacheKey, _ := payload["prompt_cache_key"].(string)
	cacheKey = normalizeCodexIdentifier(cacheKey)
	if cacheKey == "" {
		cacheKey = codexIdentifier(p.base.meta.ID + ":" + envelope.Target.UpstreamModelID)
		payload["prompt_cache_key"] = cacheKey
	}
	sessionID := firstHeader(envelope.Headers,
		"session_id", "session-id", "x-session-id", "conversation_id", "conversation-id", "x-client-request-id")
	if sessionID == "" {
		sessionID = cacheKey
	} else {
		sessionID = normalizeCodexIdentifier(sessionID)
	}
	threadID := codexIdentifier(sessionID + ":thread")
	windowID := codexIdentifier(sessionID + ":window")
	turnID := codexIdentifier(sessionID + ":turn:" + bodyDigest(payload))
	installationSeed := "cartethyia:codex:" + sessionID
	if accountID := codexAccountID(credential); accountID != "" {
		installationSeed = "cartethyia:codex:" + accountID
	}
	installationID := codexIdentifier(installationSeed)
	turnMetadata := map[string]any{
		"installation_id": installationID,
		"session_id":      sessionID,
		"thread_id":       threadID,
		"turn_id":         turnID,
	}
	metadata, _ := payload["client_metadata"].(map[string]any)
	if metadata == nil {
		metadata = map[string]any{}
	}
	metadata["installation_id"] = installationID
	metadata["session_id"] = sessionID
	metadata["thread_id"] = threadID
	metadata["turn_id"] = turnID
	turnMetadataJSON, _ := json.Marshal(turnMetadata)
	metadata["x-codex-turn-metadata"] = string(turnMetadataJSON)
	payload["client_metadata"] = metadata

	body, err := json.Marshal(payload)
	if err != nil {
		return BuiltRequest{}, fmt.Errorf("providers/codex: encode request: %w", err)
	}
	built.Endpoint = p.Endpoint(envelope.Target)
	built.Body = body
	built.Auth.Headers.Set("session_id", sessionID)
	built.Auth.Headers.Set("conversation_id", sessionID)
	built.Auth.Headers.Set("x-client-request-id", sessionID)
	built.Auth.Headers.Set("session-id", sessionID)
	built.Auth.Headers.Set("thread-id", threadID)
	built.Auth.Headers.Set("x-codex-window-id", windowID)
	built.Auth.Headers.Set("x-codex-turn-metadata", metadata["x-codex-turn-metadata"].(string))
	return built, nil
}

func firstHeader(headers http.Header, names ...string) string {
	for _, name := range names {
		if value := strings.TrimSpace(headers.Get(name)); value != "" {
			return value
		}
	}
	return ""
}

func normalizeCodexIdentifier(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if len(value) <= 64 {
		return value
	}
	return codexIdentifier(value)
}

func codexIdentifier(seed string) string {
	sum := sha256.Sum256([]byte(seed))
	return "pc_" + hex.EncodeToString(sum[:])[:61]
}

func bodyDigest(payload map[string]any) string {
	body, _ := json.Marshal(payload)
	sum := sha256.Sum256(body)
	return hex.EncodeToString(sum[:8])
}

func codexAccountID(accessToken string) string {
	parts := strings.Split(accessToken, ".")
	if len(parts) != 3 {
		return ""
	}
	decoded, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return ""
	}
	var payload struct {
		Auth struct {
			ChatGPTAccountID string `json:"chatgpt_account_id"`
		} `json:"https://api.openai.com/auth"`
	}
	if json.Unmarshal(decoded, &payload) != nil {
		return ""
	}
	return strings.TrimSpace(payload.Auth.ChatGPTAccountID)
}

func (p *CodexAdapter) ClassifyResponse(evidence ResponseEvidence) ClassifiedResponse {
	return p.base.ClassifyResponse(evidence)
}
