package apikey

func SiliconFlowCN() ProviderDefinition {
	return ProviderDefinition{
		ID: "siliconflow-cn", DisplayName: "SiliconFlow China", Protocol: ProtocolOpenAI,
		Adapter: AdapterOpenAI, CredentialKind: CredentialAPIKey,
		BaseURL: "https://api.siliconflow.cn/v1", Surfaces: []Surface{SurfaceOpenAIChat},
		ModelsDevID: "siliconflow-cn",
		Models: []ProviderModel{
			{ID: "tencent/Hunyuan-A13B-Instruct", DisplayName: "tencent/Hunyuan-A13B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "PaddlePaddle/PaddleOCR-VL-1.5", DisplayName: "PaddlePaddle/PaddleOCR-VL-1.5", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "inclusionAI/Ling-flash-2.0", DisplayName: "inclusionAI/Ling-flash-2.0", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/DeepSeek-V4-Pro", DisplayName: "deepseek-ai/DeepSeek-V4-Pro", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/DeepSeek-V3.1-Terminus", DisplayName: "deepseek-ai/DeepSeek-V3.1-Terminus", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/DeepSeek-R1", DisplayName: "deepseek-ai/DeepSeek-R1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/DeepSeek-V3.2", DisplayName: "deepseek-ai/DeepSeek-V3.2", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/DeepSeek-OCR", DisplayName: "deepseek-ai/DeepSeek-OCR", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "deepseek-ai/DeepSeek-V4-Flash", DisplayName: "DeepSeek V4 Flash", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/DeepSeek-V3", DisplayName: "deepseek-ai/DeepSeek-V3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "stepfun-ai/Step-3.5-Flash", DisplayName: "stepfun-ai/Step-3.5-Flash", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Pro/MiniMaxAI/MiniMax-M2.5", DisplayName: "Pro/MiniMaxAI/MiniMax-M2.5", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Pro/moonshotai/Kimi-K2.5", DisplayName: "Pro/moonshotai/Kimi-K2.5", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Pro/moonshotai/Kimi-K2.6", DisplayName: "Pro/moonshotai/Kimi-K2.6", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Pro/deepseek-ai/DeepSeek-V3.1-Terminus", DisplayName: "Pro/deepseek-ai/DeepSeek-V3.1-Terminus", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Pro/deepseek-ai/DeepSeek-R1", DisplayName: "Pro/deepseek-ai/DeepSeek-R1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Pro/deepseek-ai/DeepSeek-V3.2", DisplayName: "Pro/deepseek-ai/DeepSeek-V3.2", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Pro/deepseek-ai/DeepSeek-V3", DisplayName: "Pro/deepseek-ai/DeepSeek-V3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Pro/zai-org/GLM-5.1", DisplayName: "Pro/zai-org/GLM-5.1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Pro/zai-org/GLM-5", DisplayName: "Pro/zai-org/GLM-5", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "ByteDance-Seed/Seed-OSS-36B-Instruct", DisplayName: "ByteDance-Seed/Seed-OSS-36B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3.5-9B", DisplayName: "Qwen/Qwen3.5-9B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-14B", DisplayName: "Qwen/Qwen3-14B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3.5-4B", DisplayName: "Qwen/Qwen3.5-4B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3.5-122B-A10B", DisplayName: "Qwen/Qwen3.5-122B-A10B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-32B", DisplayName: "Qwen/Qwen3-32B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3-8B", DisplayName: "Qwen/Qwen3-8B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3.5-27B", DisplayName: "Qwen/Qwen3.5-27B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3.5-35B-A3B", DisplayName: "Qwen/Qwen3.5-35B-A3B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3.5-397B-A17B", DisplayName: "Qwen/Qwen3.5-397B-A17B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-235B-A22B-Thinking-2507", DisplayName: "Qwen/Qwen3-235B-A22B-Thinking-2507", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3.6-35B-A3B", DisplayName: "Qwen/Qwen3.6-35B-A3B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-VL-32B-Thinking", DisplayName: "Qwen/Qwen3-VL-32B-Thinking", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-VL-32B-Instruct", DisplayName: "Qwen/Qwen3-VL-32B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen2.5-72B-Instruct", DisplayName: "Qwen/Qwen2.5-72B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3-Coder-480B-A35B-Instruct", DisplayName: "Qwen/Qwen3-Coder-480B-A35B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen2.5-7B-Instruct", DisplayName: "Qwen/Qwen2.5-7B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3-30B-A3B-Instruct-2507", DisplayName: "Qwen/Qwen3-30B-A3B-Instruct-2507", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3-VL-30B-A3B-Thinking", DisplayName: "Qwen/Qwen3-VL-30B-A3B-Thinking", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-Coder-30B-A3B-Instruct", DisplayName: "Qwen/Qwen3-Coder-30B-A3B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "Qwen/Qwen3-VL-8B-Instruct", DisplayName: "Qwen/Qwen3-VL-8B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-VL-235B-A22B-Instruct", DisplayName: "Qwen/Qwen3-VL-235B-A22B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-VL-30B-A3B-Instruct", DisplayName: "Qwen/Qwen3-VL-30B-A3B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "Qwen/Qwen3-VL-235B-A22B-Thinking", DisplayName: "Qwen/Qwen3-VL-235B-A22B-Thinking", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "zai-org/GLM-5.2", DisplayName: "GLM-5.2", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "zai-org/GLM-4.5-Air", DisplayName: "zai-org/GLM-4.5-Air", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "baidu/ERNIE-4.5-300B-A47B", DisplayName: "baidu/ERNIE-4.5-300B-A47B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
		},
	}
}
