/** Unified storage boundary for configuration and runtime metadata. */
export { getPersistenceEnv } from "./main/env";
export type { PersistenceEnv } from "./main/env";

export {
  CONFIG_SCHEMA_SQL,
  credentialKindOf,
  createDurableRouteHealthStore,
  createDurableAccountHealthStore,
  createDurableQuotaStateStore,
  createDurableOAuthTokenStore,
  createDurableCredentialConfigStore,
  createDurableProxyPoolConfigStore,
  createConfigPersistence,
  resetConfigPersistenceForTests,
} from "./main/config";
export type {
  SettingsRecord,
  RuntimeSettings,
  ApiKeyPublic,
  ApiKeyCreateInput,
  ApiKeyUpdateInput,
  ProviderAccountRecord,
  AccountCreateInput,
  AccountPatchInput,
  AccountListPagination,
  AccountListPage,
  ProxyRecord,
  ProxyCreateInput,
  ProxyPatchInput,
  ProxySettingsRecord,
  ProviderModelRecord,
  AliasRecord,
  ComboRecord,
  CustomProviderRecord,
  AccessRuleRecord,
  SettingsRepository,
  ApiKeyRepository,
  AccountRepository,
  HealthRepository,
  ProxyRepository,
  ProviderModelRepository,
  AliasRepository,
  ComboRepository,
  CustomProviderRepository,
  AccessRuleRepository,
  ShareLinkRecord,
  ShareLinkRepository,
  ConfigPersistence,
} from "./main/config";

export {
  RUNTIME_SCHEMA_SQL,
  ensureRuntimeSchema,
  mapClientName,
  mapClientSource,
  createRuntimeTelemetryWriter,
  createRuntimeMetadataRepository,
  createConsoleLogRepository,
  retainRuntimeData,
  createRuntimePersistence,
  setRetentionDefaults,
  getRuntimePersistence,
  getRuntimeMetadataRepository,
  getConsoleLogRepository,
  resetRuntimePersistenceForTests,
  createWarpMetricsRepository,
} from "./runtime/runtime";

export {
  BACKUP_APP,
  BACKUP_VERSION,
  BACKUP_TABLES,
  MAX_BACKUP_BYTES,
  exportConfigBackup,
  validateRestorePayload,
  applyConfigRestore,
} from "./main/backup";
export type { BackupPayload, BackupTable, RestoreValidation, RestoreResult } from "./main/backup";
export type {
  RuntimeRequestRow,
  RuntimeRequestFilters,
  RuntimeRequestPage,
  UsageSummary,
  UsageCacheRow,
  UsageCacheSummary,
  ChartBucket,
  UsageByRow,
  ProviderModelTotalsRow,
  ModelTokenTotalsRow,
  ProviderTodayRow,
  ConsoleLogRow,
  ConsoleLogFilters,
  RetentionResult,
  RuntimeMetadataRepository,
  ConsoleLogRepository,
  WarpMetricRow,
  WarpMetricsSummary,
  WarpMetricsRepository,
  RuntimePersistence,
} from "./runtime/runtime";
