package builtin

func NVIDIA() ProviderDefinition {
	return ProviderDefinition{
		ID: "nvidia", DisplayName: "NVIDIA NIM", Protocol: ProtocolOpenAI,
		Adapter: AdapterOpenAI, CredentialKind: CredentialAPIKey,
		BaseURL: "https://integrate.api.nvidia.com/v1", Surfaces: []Surface{SurfaceOpenAIChat},
		ModelsDevID: "nvidia",
		Models: []ProviderModel{
			{ID: "nvidia/llama-3.3-nemotron-super-49b-v1", DisplayName: "Llama 3.3 Nemotron Super 49B v1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/nemotron-3-nano-30b-a3b", DisplayName: "nemotron-3-nano-30b-a3b", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/active-speaker-detection", DisplayName: "Active Speaker Detection", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/llama-3.1-nemotron-nano-8b-v1", DisplayName: "Llama 3.1 Nemotron Nano 8B v1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/gliner-pii", DisplayName: "gliner-pii", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/nemotron-3-content-safety", DisplayName: "nemotron-3-content-safety", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/cosmos-transfer2_5-2b", DisplayName: "cosmos-transfer2.5-2b", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/llama-3.1-nemotron-70b-instruct", DisplayName: "Llama 3.1 Nemotron 70B Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "nvidia/nemotron-nano-12b-v2-vl", DisplayName: "Nemotron Nano 12B v2 VL", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "nvidia/nemotron-voicechat", DisplayName: "nemotron-voicechat", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "nvidia/studiovoice", DisplayName: "studiovoice", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/llama-nemotron-rerank-vl-1b-v2", DisplayName: "llama-nemotron-rerank-vl-1b-v2", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/llama-3.3-nemotron-super-49b-v1.5", DisplayName: "Llama 3.3 Nemotron Super 49B v1.5", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/llama-3_2-nemoretriever-300m-embed-v1", DisplayName: "llama-3_2-nemoretriever-300m-embed-v1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/nemotron-3-super-120b-a12b", DisplayName: "Nemotron 3 Super", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", DisplayName: "Nemotron 3 Nano Omni", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "nvidia/rerank-qa-mistral-4b", DisplayName: "rerank-qa-mistral-4b", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/nv-embed-v1", DisplayName: "nv-embed-v1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/cosmos-transfer1-7b", DisplayName: "cosmos-transfer1-7b", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/streampetr", DisplayName: "streampetr", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/nv-embedcode-7b-v1", DisplayName: "nv-embedcode-7b-v1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/usdvalidate", DisplayName: "usdvalidate", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/nemotron-content-safety-reasoning-4b", DisplayName: "nemotron-content-safety-reasoning-4b", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: false, Images: false}},
			{ID: "nvidia/nemotron-3-ultra-550b-a55b", DisplayName: "Nemotron 3 Ultra 550B A55B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/cosmos-predict1-5b", DisplayName: "cosmos-predict1-5b", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/magpie-tts-zeroshot", DisplayName: "magpie-tts-zeroshot", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/nvidia-nemotron-nano-9b-v2", DisplayName: "nvidia-nemotron-nano-9b-v2", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/nemotron-3.5-lightning-30b-a3b", DisplayName: "Nemotron 3.5 Lightning 30B A3B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/riva-translate-4b-instruct-v1.1", DisplayName: "riva-translate-4b-instruct-v1_1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/llama-3.1-nemotron-ultra-253b-v1", DisplayName: "Llama 3.1 Nemotron Ultra 253B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "nvidia/sparsedrive", DisplayName: "sparsedrive", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/usdcode", DisplayName: "usdcode", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3", DisplayName: "llama-3.1-nemotron-safety-guard-8b-v3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "nvidia/bevformer", DisplayName: "bevformer", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/cosmos-reason2-8b", DisplayName: "Cosmos Reason2 8B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", DisplayName: "Llama 3.1 Nemotron Nano VL 8B v1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "nvidia/nemotron-mini-4b-instruct", DisplayName: "nemotron-mini-4b-instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "nvidia/llama-nemotron-embed-vl-1b-v2", DisplayName: "llama-nemotron-embed-vl-1b-v2", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "nvidia/synthetic-video-detector", DisplayName: "synthetic-video-detector", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "microsoft/phi-4-multimodal-instruct", DisplayName: "Phi 4 Multimodal", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "microsoft/phi-4-mini-instruct", DisplayName: "Phi-4-Mini", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "z-ai/glm-5.2", DisplayName: "GLM-5.2", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "google/gemma-3n-e2b-it", DisplayName: "Gemma 3n E2b It", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "google/google-paligemma", DisplayName: "paligemma", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "google/gemma-3-4b-it", DisplayName: "Gemma 3 4B IT", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "google/gemma-4-31b-it", DisplayName: "Gemma-4-31B-IT", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "google/gemma-3n-e4b-it", DisplayName: "Gemma 3n E4b It", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "google/gemma-3-12b-it", DisplayName: "Gemma 3 12B IT", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "google/gemma-2-2b-it", DisplayName: "Gemma 2 2b It", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "meta/llama-3.2-3b-instruct", DisplayName: "Llama 3.2 3B Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "meta/esmfold", DisplayName: "esmfold", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "meta/llama-3.3-70b-instruct", DisplayName: "Llama 3.3 70b Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "meta/llama-guard-4-12b", DisplayName: "Llama Guard 4 12B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "meta/llama-3.2-1b-instruct", DisplayName: "Llama 3.2 1b Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "meta/llama-3.1-8b-instruct", DisplayName: "Llama 3.1 8B Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "meta/llama-3.1-70b-instruct", DisplayName: "Llama 3.1 70b Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "meta/esm2-650m", DisplayName: "esm2-650m", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "meta/llama-3.2-90b-vision-instruct", DisplayName: "Llama-3.2-90B-Vision-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "meta/llama-3.2-11b-vision-instruct", DisplayName: "Llama 3.2 11b Vision Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "meta/llama-4-maverick-17b-128e-instruct", DisplayName: "Llama 4 Maverick 17b 128e Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "poolside/laguna-xs-2.1", DisplayName: "Laguna XS 2.1", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "bytedance/seed-oss-36b-instruct", DisplayName: "ByteDance-Seed/Seed-OSS-36B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "openai/whisper-large-v3", DisplayName: "Whisper Large v3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "openai/gpt-oss-120b", DisplayName: "GPT-OSS-120B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "openai/gpt-oss-20b", DisplayName: "GPT OSS 20B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/deepseek-v4-flash", DisplayName: "DeepSeek V4 Flash", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "deepseek-ai/deepseek-v4-pro", DisplayName: "DeepSeek V4 Pro", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "stepfun-ai/step-3.5-flash", DisplayName: "Step 3.5 Flash", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "stepfun-ai/step-3.7-flash", DisplayName: "Step 3.7 Flash", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "baai/bge-m3", DisplayName: "BGE M3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "qwen/qwen3.5-397b-a17b", DisplayName: "Qwen3.5-397B-A17B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "qwen/qwen-image", DisplayName: "Qwen Image", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "qwen/qwen3-coder-480b-a35b-instruct", DisplayName: "Qwen3 Coder 480B A35B Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "qwen/qwen2.5-coder-32b-instruct", DisplayName: "Qwen2.5 Coder 32b Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "qwen/qwen3-next-80b-a3b-instruct", DisplayName: "Qwen3-Next-80B-A3B-Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "qwen/qwen3.5-122b-a10b", DisplayName: "Qwen3.5 122B-A10B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "qwen/qwen-image-edit", DisplayName: "Qwen Image Edit", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "abacusai/dracarys-llama-3.1-70b-instruct", DisplayName: "dracarys-llama-3.1-70b-instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "thinkingmachines/inkling", DisplayName: "Inkling", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "mistralai/magistral-small-2506", DisplayName: "Magistral Small 2506", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "mistralai/mistral-7b-instruct-v0.3", DisplayName: "Mistral-7B-Instruct-v0.3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "mistralai/mistral-large-3-675b-instruct-2512", DisplayName: "Mistral Large 3 675B Instruct 2512", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "mistralai/mistral-nemotron", DisplayName: "mistral-nemotron", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "mistralai/mistral-small-4-119b-2603", DisplayName: "mistral-small-4-119b-2603", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "mistralai/mixtral-8x7b-instruct", DisplayName: "Mistral: Mixtral 8x7B Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "mistralai/mistral-medium-3.5-128b", DisplayName: "Mistral Medium 3.5", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "mistralai/mixtral-8x22b-instruct", DisplayName: "Mistral: Mixtral 8x22B Instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "mistralai/mistral-medium-3-instruct", DisplayName: "Mistral Medium 3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "mistralai/ministral-14b-instruct-2512", DisplayName: "Ministral 3 14B Instruct 2512", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: true}},
			{ID: "minimaxai/minimax-m3", DisplayName: "MiniMax-M3", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: true}},
			{ID: "minimaxai/minimax-m2.7", DisplayName: "MiniMax-M2.7", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: true, ToolCalls: true, Images: false}},
			{ID: "upstage/solar-10.7b-instruct", DisplayName: "solar-10.7b-instruct", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "sarvamai/sarvam-m", DisplayName: "sarvam-m", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: true, Images: false}},
			{ID: "black-forest-labs/flux_2-klein-4b", DisplayName: "FLUX.2 Klein 4B", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
			{ID: "black-forest-labs/flux.1-dev", DisplayName: "FLUX.1-dev", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "black-forest-labs/flux_1-schnell", DisplayName: "FLUX.1-schnell", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: false}},
			{ID: "black-forest-labs/flux_1-kontext-dev", DisplayName: "FLUX.1-Kontext-dev", Capabilities: &ProviderCaps{Surfaces: []Surface{SurfaceOpenAIChat}, Streaming: true, Reasoning: false, ToolCalls: false, Images: true}},
		},
	}
}
